### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [sebastienfilion/zsh.newton#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by sebastienfilion** [comment]
Hey @unixorn 👋 I added a MIT license file, hope that works. https://github.com/sebastienfilion/zsh.newton/commit/38dc6277926ba4294e513d3593409a9a3fb99d2f
I didn't made this theme very configurable, if someone want more flexibility, I'm open to make changes.
